name: 🐛 Bug Report
description: Report a bug with schemas, validation, or tooling
title: "[Bug]: "
labels: [bug, needs-triage]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This template helps us gather the information needed to investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Run command `python scripts/validate.py examples/site.json`
        2. See error message...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Schema (organization, site, asset, etc.)
        - Validation script
        - Type generation
        - Examples
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: input
    id: schema-version
    attributes:
      label: Schema Version
      description: Which schema version are you using?
      placeholder: v0.1

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: macOS 14.0
        - Python: 3.11.5
        - jsonschema: 4.23.0
      value: |
        - OS: 
        - Python: 
        - jsonschema: 

  - type: textarea
    id: data-sample
    attributes:
      label: Sample Data
      description: Provide sample JSON data that triggers the bug (anonymized)
      render: json
      placeholder: |
        {
          "id": "sit_example",
          "name": "Example Site"
        }

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Paste any error messages or logs
      render: shell
      placeholder: |
        Error: ValidationError at root -> location: 'latitude' is a required property

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have provided sample data that reproduces the issue
          required: false
        - label: I am willing to help test a fix
          required: false