name: 📚 Documentation
description: Report issues or suggest improvements to documentation
title: "[Docs]: "
labels: [documentation, enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation! Whether it's fixing errors, adding examples, or clarifying concepts.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What kind of documentation issue is this?
      options:
        - Fix error or typo
        - Add missing information
        - Improve clarity
        - Add examples
        - Update outdated content
        - New documentation needed
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue?
      options:
        - README.md
        - CONTRIBUTING.md
        - Schema conventions
        - Standards mapping
        - API documentation
        - Examples
        - Comments in schemas
        - Other
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the documentation issue or improvement needed
      placeholder: |
        The example for the asset schema is missing the required 'type' field,
        which causes validation to fail when users try to follow the example.
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content (if applicable)
      description: Quote the current documentation that needs fixing
      placeholder: |
        Current documentation says:
        "All timestamps must be in ISO 8601 format"
        
        But it should specify UTC timezone requirement.

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Add explicit UTC timezone requirement:
        "All timestamps must be in ISO 8601 format with UTC timezone (ending in 'Z')"
        
        Example: "2025-01-15T10:30:00Z"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context about why this improvement is needed
      placeholder: |
        Users frequently ask about timezone handling in our Discord channel,
        indicating this is a common source of confusion.

  - type: checkboxes
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      options:
        - label: New users getting started
        - label: Developers integrating schemas
        - label: Schema contributors
        - label: API implementers
        - label: Standards organizations

  - type: checkboxes
    id: help-wanted
    attributes:
      label: Contribution
      description: Are you willing to help improve the documentation?
      options:
        - label: I can fix this myself and submit a PR
        - label: I can provide more examples or use cases
        - label: I can review improvements made by others
        - label: I can help identify related documentation issues